# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pub_date', models.DateField(default=None)),
                ('dat', models.DateField(default=None)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'article',
                'managed': True,
            },
        ),
    ]
