# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dat',
            field=models.DateField(default=None, null=True),
        ),
    ]
